GET http://localhost:8080/admin/logs

###
POST http://localhost:8080/admin/logs
Content-Type: application/json

{
  "user_id": "a1b2c3d4-e5f6-7890-abcd-1234567890ab",
  "action": "Login",
  "entity_id": "3fa85f64-5717-4562-b3fc-2c963f66afa6"
}

###
POST http://localhost:8080/admin/logs
Content-Type: application/json

{
  "user_id": "b7c9d123-45e6-4a9f-8c21-9d123456abcd",
  "action": "CREATE_DOCUMENT",
  "entity_id": "4fa85f64-5717-4562-b3fc-2c963f66afa7"
}
