package com.dms.service;

import com.dms.dto.UserSignatureRequest;
import com.dms.models.UserSignature;
import com.dms.dao.UserSignatureRepository;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import java.time.OffsetDateTime;
import java.util.Base64;
import java.util.List;
import java.util.UUID;

@Service
public class SignatureService {

    private final UserSignatureRepository userSignatureRepository;

    public SignatureService(UserSignatureRepository userSignatureRepository) {
        this.userSignatureRepository = userSignatureRepository;
    }

    public List<UserSignature> getUserSignatures(UUID userId) {
        return userSignatureRepository.findByUserIdAndDeletedAtIsNull(userId);
    }

    @Transactional
    public UserSignature saveUserSignature(UUID userId, UserSignatureRequest request) {
        if (request.isDefault()) {
            userSignatureRepository.clearDefaultStatusForUser(userId);
        }

        UserSignature signature = new UserSignature();
        signature.setUserId(userId);
        signature.setLabel(request.getLabel());

        if (request.getSignatureType() != null) {
            signature.setSignatureType(request.getSignatureType().toUpperCase());
        }

        signature.setDefault(request.isDefault());

        // Process the incoming image string cleanly
        if (request.getSignatureDataUrl() != null && request.getSignatureDataUrl().contains(",")) {
            // Split out the header (e.g., "data:image/png;base64,")
            String base64ImageBytes = request.getSignatureDataUrl().split(",")[1];

            // 🔥 FIX: Clean out hidden whitespaces/newlines generated by Type/Upload canvas strings
            base64ImageBytes = base64ImageBytes.replaceAll("\\s", "");

            try {
                byte[] imageBytes = Base64.getDecoder().decode(base64ImageBytes);
                signature.setSignatureImage(imageBytes);
            } catch (IllegalArgumentException e) {
                System.err.println("Base64 Decoding failed for Type/Upload tab: " + e.getMessage());
                // Fallback decode method for non-standard or padded Base64 payloads
                byte[] imageBytes = Base64.getMimeDecoder().decode(base64ImageBytes);
                signature.setSignatureImage(imageBytes);
            }
        }

        return userSignatureRepository.save(signature);
    }

    @Transactional
    public void softDeleteSignature(UUID signatureId) {
        userSignatureRepository.findByUserSignatureIdAndDeletedAtIsNull(signatureId)
                .ifPresent(sig -> {
                    sig.setDeletedAt(OffsetDateTime.now());
                    sig.setDefault(false);
                    userSignatureRepository.save(sig);
                });
    }
}